project:
  type: website

website:
  title: "Andy Nguyen"
  search: false
  navbar:
    left:
      - href: shorts/index.qmd
        text: Short Posts

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: "left"
    toc-title: "On this page"


execute:
  python: .venv/bin/python